//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TecnicoWeb3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Etapa
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Etapa()
        {
            this.Repuestos = new HashSet<Repuestos>();
        }
    
        public int IdEtapa { get; set; }
        public string Descripcion { get; set; }
        public System.DateTime FechaIngreso { get; set; }
        public string Tecnico_DNI { get; set; }
        public string Nombre_Etapa { get; set; }
        public int Solicitud_Reparacion_idProblema { get; set; }
    
        public virtual Solicitud_Reparacion Solicitud_Reparacion { get; set; }
        public virtual Tecnico Tecnico { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Repuestos> Repuestos { get; set; }
    }
}
