//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TecnicoWeb3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Repuestos
    {
        public int idRepuesto { get; set; }
        public string NombreRepuesto { get; set; }
        public int Cantidad { get; set; }
        public int Etapa_IdEtapa { get; set; }
        public string Etapa_Tecnico_DNI { get; set; }
        public int Etapa_Solicitud_Reparacion_idProblema { get; set; }
    
        public virtual Etapa Etapa { get; set; }
    }
}
