//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TecnicoWeb3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Solicitud_Reparacion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Solicitud_Reparacion()
        {
            this.Etapa = new HashSet<Etapa>();
        }
    
        public int IdSolicitud { get; set; }
        public string NombreSolicitud { get; set; }
        public string Descripcion { get; set; }
        public int Cotizacion { get; set; }
        public System.DateTime FechaSolicitud { get; set; }
        public int Producto_IdProducto { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Etapa> Etapa { get; set; }
        public virtual Producto Producto { get; set; }
    }
}
